# Generated by Django 3.0 on 2021-02-24 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orbis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essence',
            name='child',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orbis_app.Essence'),
        ),
        migrations.AlterField(
            model_name='essence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
