# Generated by Django 3.0 on 2021-02-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orbis_app', '0002_auto_20210224_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essence',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orbis_app.Essence'),
        ),
    ]
