# Generated by Django 3.0 on 2021-02-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orbis_app', '0003_auto_20210226_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essence',
            old_name='child',
            new_name='parent',
        ),
    ]
